parameters:
- name: artifactName
  type: string
  default: 'frontend'

steps:
- task: NodeTool@1
  inputs:
    version: '22.x'
  displayName: Install Node.js

- script: |
    node --version
    npm --version
  displayName: Check Node.js Version

- script: |
    npm ci
  displayName: Install Dependencies
  workingDirectory: $(System.DefaultWorkingDirectory)/frontend

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: 'build'
    repository: 'samlapointe01/axie-analytics'
    dockerfile: '$(System.DefaultWorkingDirectory)/frontend/Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)/frontend'
    tags: |
      frontend-$(Build.BuildId)
      frontend-latest

- task: Docker@2
  displayName: Push Docker Image
  inputs:
    command: 'push'
    repository: 'samlapointe01/axie-analytics'
    containerRegistry: 'Docker Hub'
    tags: |
      frontend-$(Build.BuildId)
      frontend-latest